OrdererOrgs:
  - Name: Orderer
    Domain: test.net
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer
PeerOrgs:
  - Name: Org1
    Domain: org1.test.net
    EnableNodeOUs: true
    Template:
      Count: 1
      SANS:
        - localhost
        - peer0.org1.test.net
    Users:
      Count: 1
  - Name: Org2
    Domain: org2.test.net
    EnableNodeOUs: true
    Template:
      Count: 1
      SANS:
        - localhost
        - peer0.org1.test.net
    Users:
      Count: 1
