networks:
  fabric-test-net:
    name: fabric-test-net
    

volumes:
  orderer.test.net:
  peer0.org1.test.net:
  peer0.org2.test.net:

services:
  orderer.test.net:
    container_name: orderer.test.net
    image: hyperledger/fabric-orderer:latest
    volumes:
      - ./organizations/ordererOrganizations/test.net/orderers/orderer.test.net/msp:/var/hyperledger/orderer/msp
      - ./organizations/ordererOrganizations/test.net/orderers/orderer.test.net/tls/:/var/hyperledger/orderer/tls
      - orderer.test.net:/var/hyperledger/production/orderer
    command: orderer
    working_dir: /root
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=7050
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_GENERAL_BOOTSTRAPMETHOD=none
      - ORDERER_CHANNELPARTICIPATION_ENABLED=true
      - ORDERER_ADMIN_TLS_ENABLED=true
      - ORDERER_ADMIN_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_ADMIN_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_ADMIN_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_ADMIN_TLS_CLIENTROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_ADMIN_LISTENADDRESS=0.0.0.0:7054
      - ORDERER_METRICS_PROVIDER=prometheus
      - ORDERER_OPERATIONS_LISTENADDRESS=0.0.0.0:8443
      - ORDERER_OPERATIONS_TLS_ENABLED=false
    ports:
      - 7050:7050
      - 7054:7054
      - 9050:8443
    networks:
      fabric-test-net:
        aliases:
          - orderer.test.net
      
  peer0.org1.test.net:
    container_name: peer0.org1.test.net
    image: hyperledger/fabric-peer:latest
    environment:
      - FABRIC_CFG_PATH=/etc/hyperledger/fabric
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_PEER_ID=peer0.org1.test.net
      - CORE_PEER_ADDRESS=peer0.org1.test.net:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.org1.test.net:10001
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:10001
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.test.net:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.test.net:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_METRICS_PROVIDER=prometheus
      - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:8443
      - CORE_OPERATIONS_TLS_ENABLED=false
    volumes:
      - ./organizations/peerOrganizations/org1.test.net/peers/peer0.org1.test.net/msp:/etc/hyperledger/fabric/msp
      - ./organizations/peerOrganizations/org1.test.net/peers/peer0.org1.test.net/tls:/etc/hyperledger/fabric/tls
      - peer0.org1.test.net:/var/hyperledger
    working_dir: /root
    command: peer node start
    ports:
      - 7051:7051
      - 9051:8443
    networks:
      fabric-test-net:
        aliases:
          - peer0.org1.test.net

  peer0.org2.test.net:
    container_name: peer0.org2.test.net
    image: hyperledger/fabric-peer:latest
    environment:
      - FABRIC_CFG_PATH=/etc/hyperledger/fabric
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_PEER_ID=peer0.org2.test.net
      - CORE_PEER_ADDRESS=peer0.org2.test.net:7052
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_CHAINCODEADDRESS=peer0.org2.test.net:10002
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:10002
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org2.test.net:7052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org2.test.net:7052
      - CORE_PEER_LOCALMSPID=Org2MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_METRICS_PROVIDER=prometheus
      - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:8443
      - CORE_OPERATIONS_TLS_ENABLED=false
    volumes:
      - ./organizations/peerOrganizations/org2.test.net/peers/peer0.org2.test.net/msp:/etc/hyperledger/fabric/msp
      - ./organizations/peerOrganizations/org2.test.net/peers/peer0.org2.test.net/tls:/etc/hyperledger/fabric/tls
      - peer0.org2.test.net:/var/hyperledger
    working_dir: /root
    command: peer node start
    ports:
      - 7052:7052
      - 9052:8443
    networks:
      fabric-test-net:
        aliases:
          - peer0.org2.test.net

  cli-org1_2:
    container_name: cli.test.net
    image: hyperledger/fabric-tools:latest
    tty: true
    stdin_open: true
    environment:
      - SYS_CHANNEL=$SYS_CHANNEL
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.org1.test.net:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations/peerOrganizations/org1.test.net/peers/peer0.org1.test.net/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations/peerOrganizations/org1.test.net/peers/peer0.org1.test.net/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations/peerOrganizations/org1.test.net/peers/peer0.org1.test.net/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations/peerOrganizations/org1.test.net/users/Admin@org1.test.net/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./organizations:/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.test.net
      - peer0.org1.test.net
      - peer0.org2.test.net
    networks:
      fabric-test-net:
        aliases:
          - cli.test.net
