networks:
  fabric-test-net:
    name: fabric-test-net
    external: true

volumes:
  prom-data:

services:
  grafana:
    image: grafana/grafana
    container_name: grafana.test.net
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - ./grafana:/etc/grafana/provisioning
    depends_on:
      - prometheus
    networks:
      fabric-test-net:
        aliases:
          - grafana.monitoring.test.net

  prometheus:
    image: prom/prometheus
    container_name: prometheus.test.net
    restart: always
    ports:
      - 9090:9090
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prom-data:/prometheus
    depends_on:
      - node-exporter
      - cadvisor
    networks:
      fabric-test-net:
        aliases:
          - prometheus.monitoring.test.net

  node-exporter:
    image: prom/node-exporter
    container_name: node.test.net
    restart: always
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      - /:/host:ro,rslave
    command:
      - '--path.rootfs=/host'
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    networks:
      fabric-test-net:
        aliases:
          - node-exporter.monitoring.test.net

  cadvisor:
    image: gcr.io/cadvisor/cadvisor
    container_name: cadvisor.test.net
    restart: always
    devices:
      - "/dev/kmsg:/dev/kmsg"
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    networks:
      fabric-test-net:
        aliases:
          - cadvisor.monitoring.test.net

