global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter.monitoring.test.net:9100']
        labels:
          instance: host
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor.monitoring.test.net:8080']
        labels:
          instance: containers
  - job_name: 'hyperledger-fabric'
    static_configs:
      - targets: ['orderer.test.net:8443','peer0.org1.test.net:8443','peer0.org2.test.net:8443','peer0.org3.test.net:8443']
        labels:
          instance: HLF