{
 "title": "Docker stas",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Memory usage (Gb)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "peer0.org1",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{name=\"peer0.org1.test.net\"} / 1073741824",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "peer0.org2",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{name=\"peer0.org2.test.net\"} / 1073741824",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "peer0.org3",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{name=\"peer0.org3.test.net\"} / 1073741824",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "chaincode",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{name=\"chaincode.test.net\"} / 1073741824",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "orderer",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{name=\"orderer.test.net\"} / 1073741824",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "grafana",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{name=\"grafana.test.net\"} / 1073741824",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "FileSystem usage (Mb)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "peer0.org1",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_fs_usage_bytes{name=\"peer0.org1.test.net\"} / 1048576",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "peer0.org2",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_fs_usage_bytes{name=\"peer0.org2.test.net\"} / 1048576",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "peer0.org3",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_fs_usage_bytes{name=\"peer0.org3.test.net\"} / 1048576",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "chaincode",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_fs_usage_bytes{name=\"chaincode.test.net\"} / 1048576",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "orderer",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_fs_usage_bytes{name=\"orderer.test.net\"} / 1048576",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "grafana",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_fs_usage_bytes{name=\"grafana.test.net\"} / 1048576",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}