{
 "title": "Server stas",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "load 1m",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_load1", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "load 5m",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_load5", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "load 15m",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_load15", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "cpu seconds",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(cpu) (rate(node_cpu_seconds_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "MEM free (GB)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes/1073741824",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MEM free",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 10 },
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes/1073741824",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SWAP free (GB)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_SwapFree_bytes/1073741824",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SWAP free",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 18 },
   "targets": [
    {
     "expr": "node_memory_SwapFree_bytes/1073741824",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Free (GB)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{device=\"/dev/sda1\"}/1073741824",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "write time seconds total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 6, "y": 27 },
   "targets": [
    {
     "expr": "rate(node_disk_write_time_seconds_total{device=\"sda\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "read time seconds total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 27 },
   "targets": [
    {
     "expr": "rate(node_disk_read_time_seconds_total{device=\"sda\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}