# Configuration file version
apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    uid: prometheus-datasource
    url: http://prometheus.monitoring.test.net:9090
    version: 1
    editable: true